### ISSUE TITLE
definition of gradf (Gradient of data fidelity term (f))

### ISSUE THREAD

**Issue by dawnlh** [rgavaska/plug-and-play-ISTA#1]
Hi~ 
In line 15 of ‘demo_inpainting.m’ ,  you define the 'Gradient of data fidelity term (f)' as `gradf = @(x) P.*(x-b);`. I want to know why it's not `gradf = @(x) P.*(P.*x-b)`, which is the gradient of ` f  = 1/2*(P.*x-b).^2`.  I try the latter definition, and the result PSNR is very close to the original definition. Confusing~

**Comment by rgavaska** [comment]
`P` is a binary matrix (i.e. every entry is either 0 or 1). Hence, `P.*P = P`. So you can define the gradient either way; it makes no difference.
